name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          # Run flake8 on all Python files, ignoring selected warnings
          flake8 . --count --select=E,F,W,C90 --ignore=E121,E122,E226,E501,E999,F821,F401 --show-source --statistics
          echo "Python linting complete (with specified rules ignored)"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install -g jshint@2.13.4

      - name: Run JSHint
        run: |
          # Collect all .js files under ./server/database and pass them all at once to jshint
          jshint --esversion=6 $(find ./server/database -name "*.js")
          echo "JavaScript linting complete"

